# Generated by Django 3.2.13 on 2022-04-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20220425_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='gander',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='student',
            name='auto_gen_identification',
            field=models.BooleanField(default=True),
        ),
    ]
