# Generated by Django 3.2.13 on 2022-04-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20220426_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='identification',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
