name: Manatal Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Django Testing
        run: |
          python3 manage.py test
      - name: Django migrations
        run: |
          python manage.py migrate
      - name: Start django Server
        run: |
          python manage.py runserver 0.0.0.0:8000         
